# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxzVGYXyjlDGPrRLXgcPCqHPsPM-IRvg
"""

if __name__ == '__main__':
    print("Hello, World!")

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)

if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i*i)

def is_leap(year):
    leap = False

    # Write your logic
    if (year%400==0) or (year%4==0 and year%100!=0):
        leap=True

    return leap
print(is_leap(2000))

if __name__ == '__main__':
    n = int(input())
    res = ""
    for i in range(1, n + 1):
        res += str(i)
    print(res)











